name: Grading Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Download latest test files
      run: |
        # Create the target directory if it doesn't exist
        mkdir -p .github/tests
        curl -o .github/tests/test_assignment.py https://raw.githubusercontent.com/UCSF-DataSci/datasci223_assignment4/main/.github/tests/test_assignment.py

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest numpy pandas scipy statsmodels scikit-learn matplotlib seaborn pywt nbformat

    - name: Setup Jupyter Kernel
      run: |
        pip install ipykernel
        python -m ipykernel install --user --name=python3 --display-name="Python 3"

    - name: Run tests
      run: |
        pytest .github/tests/test_assignment.py -v